config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about'=>'homes#about',  as:'about'
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def favorited_by?(user)
    favorites.exists?(user_id: user_id)
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

 def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top, :about]
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      redirect_to book_path(@book), notice: 'You have creatad book successfully.'
    else
      @books = Book.all
      render :index
    end
  end


  def show
    @book=Book.find(params[:id])
  end

  def index
    @book=Book.new
    @books=Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book=Book.find(paramas[:post_image_id])
    favorite=current_user.favorites.new(book_id: book_id)
    favorite.save
    redirect_to books_path(book)
  end

  def destroy
    book=book.find(paramas[:book_id])
    favorite=current_user.favorites.find_by(book_id: book_id)
    favorite.destroy
    redirect_to books_path(book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]


  def index
    @user=current_user
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @books=@user.books
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  private
  def user_params
   params.require(:user).permit(:name, :profile_image, :introduction)
  end

   def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<%= form_with model: book  do |f| %>
  <div class="form-group">
    <%= f.label :title, class:'control-label' %>
    <%= f.text_field :title, class:'form-control input-sm' %>
  </div>

  <div class="form-group">
    <%= f.label :body, 'Opinion', class:'control-label' %>
    <%= f.text_area :body, class:'form-control input-sm' %>
  </div>

  <div class="form-group">
    <%= f.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/books/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Title</th>
      <th scope="col">Opinion</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user_id) do %>
          <% if user.profile_image.attached? %>
           <%= image_tag user.get_profile_image(40,40) %>
         <% else %>
          <%= image_tag 'no_image', size: "40x40" %>
         <% end %>
       <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      <td>
        <%= if @book.favorited_by?(current_user) %>
           <%= link_to book_favorites_path(@book), method: :delete do %>
            ♥<%= @book.favorites.count %>
           <% end %>
        <% else %>
           <%= link_to book_favorites_path(@book), method: :post do %>
            ♡<%=@book.favorites.count %>
           <% end %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">

  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>

      <% if @book.errors.any? %>
     <div class="text-danger">
       <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
     </div>
    <% end %>

      <%= form_with model: @book, url: book_path, method: :patch  do |f| %>

        <div class="form-group">
          <label for="input Title">Title</label>
          <%= f.text_field :title, autofocus: true, id:"inputTitle", class:'form-control' %>
        </div>

        <div class="form-group">
          <label for="input Opinion">Opinion</label>
          <%= f.text_area :body, autofocus: true, id:"inputOpinion", class:'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit "Update Book", class:'btn btn-success' %>
        </div>

        <%= link_to "Show", book_path %>
        |
        <%= link_to "Back", books_path(@books) %>

      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">

     <% if @book.errors.any? %>
     <div class="text-danger">
       <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
     </div>
    <% end %>


  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/user_info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/new', book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
       <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Title</th>book
              <th scope="col">Opinion</th>
            </tr>
          </thead>

          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <% if book.user.profile_image.attached? %>
                   <%= image_tag book.user.get_profile_image(40,40) %>
                 <% else %>
                  <%= image_tag 'no_image', size: "40x40" %>
                 <% end %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p class="text-success"><%= notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/user_info', user: @book.user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/new', book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
       <tbody>
         <th scope="row">
           <tr>
             <td>
               <%= link_to user_path(@book.user_id) do %>
                 <% if @book.user.profile_image.attached? %>
                   <%= image_tag @book.user.get_profile_image(40,40) %>
                   <br>
                   <%= @book.user.name %>
                 <% else %>
                    <%= image_tag 'no_image', size: "40x40" %>
                    <br>
                    <%= @book.user.name %>
                 <% end %>
               <% end %>
             </td>
             <td><%= @book.title %></td>
             <td><%= @book.body %></td>
             <% if @book.user == current_user %>
             <td><%= link_to "Edit", edit_book_path(@book), class:'btn btn-success' %></td>
             <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm"=>"本当に削除しますか？", class:'btn btn-danger' %></td>
             <% end %>
             </tr>
           </th>
       </tbody>
     </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i>
    <strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<p class="text-success"><%= notice %></p>
<div class="container">
	<p id="notice"></p>
  <div class="row">
	<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
		
	  <div class="top-text">
		<h1>welcom to
		  <i class="fas fa-book"></i>
		  <b>Bookers!!</b>
		</h1>
		<p>In
		  <i class="fas fa-book"></i>
		  <b>Bookers</b>,
		  	<p>you can share and exchange your opinions , inpresiions , and emotions</p>
		  	<p>about various books!</p>
		</p>
	  </div>
		
	<div class="btn-wrapper col-10 mx-auto">
		<div class="row">
	      <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
		</div>
		<div class="row">
		  <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block mb-3" %>
		</div>
	</div>
		
  </div>
</div>

app/views/layouts/_errors_messages.html.erb
<div class="text-danger">
  <% if errors.errors.any? %>
    <h3><%= errors.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
    <% errors.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="container mt-5">
  <div class="row">
    <div class="mx-auto">
      <p>
        <small>CopyRight Infratop.inc</small>
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
       <li class="navbar-brand p-3"><%= link_to 'Bookers', root_path, class:"nav-link text-white" %></li>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>



      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>

            <li class="nav-item">
              <%= link_to user_path(current_user) do %>
              <div class="nav-link text-white"><i class="fas fa-home"></i>Home</div>
              <% end  %>
            </li>

            <li class="nav-item">
              <%= link_to users_path do %>
              <div class='nav-link text-white'><i class="fas fa-users"></i>Users</div>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to books_path do %>
              <div class='nav-link text-white'><i class="fas fa-book-open"></i>Books</div>
              <% end %>
            </li>


            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete do %>
              <div class='nav-link text-white'><i class="fas fa-sign-out-alt"></i>Log out</div>
              <% end %>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to root_path do %>
              <div class='nav-link text-white'><i class="fas fa-home"></i>Home</div>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to about_path do %>
              <div class='nav-link text-white'><i class="fas fa-link"></i>About</div>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to  new_user_registration_path do %>
              <div class='nav-link text-white'><i class="fas fa-user-plus"></i>Sign up</div>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to  new_user_session_path do %>
              <div class='nav-link text-white'><i class="fas fa-sign-in-alt"></i>Log in</div>
              <% end %>
            </li>

          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body classs="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    
     <main class="mb-auto">
    <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/users/_table.html.erb
<table class="table table-hover">
       <thead>
         <th scope="col">image</th>
         <th scope="col">name</th>
         <th scope="colspan="3""></th>
       </thead>

       <tbody>
         <th scope="row">
           <% @users.each do |user| %>
           <tr>
             <td>
               <% if user.profile_image.attached? %>
                 <%= image_tag user.profile_image, size: "40x40" %>
               <% else %>
                <%= image_tag 'no_image', size: "40x40" %>
               <% end %>
             </td>
             <td><%= user.name %></td>
             <td><%= link_to "Show", user_path(user.id) %></td>
             </tr>
        <% end %>
           </th>
       </tbody>
     </table>

app/views/users/_user_info.html.erb
<table class="table">
  <tr>
    <%= image_tag user.get_profile_image(100,100)  %>
  </tr>
  <tr>
    <th>name</th>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <th>introduction</th>
    <td><%= user.introduction %></td>
  </tr>
</table>

<div>
  <%= link_to edit_user_path(user) do %>
  <div class="btn btn-outline-secondary btn-block"><i class="fas fa-user-cog"></i></div>
  <% end %>
</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

     <% if @user.errors.any? %>
       <div class="text-danger">
         <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
       </div>
      <% end %>

      <%= form_with model: @user do |f| %>

        <div class="form-group">
          <label for="input Name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", class:'form-control' %>
        </div>

        <div class="form-group">
          <label for="input Image">Image</label>
          <%= f.file_field :profile_image,  accept: "image/*", class:'form-control-file' %>
        </div>

        <div class="form-group">
          <label for="input Introduction">Introduction</label>
          <%= f.text_area :introduction, autofocus: true, id:"inputName", class:'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit "Update User", class:'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/user_info', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/new', book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'users/table', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p class="text-success"><%= notice %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'user_info', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/new', book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'books/table', books: @books, user: @user  %>
    </div>
  </div>
</div>